---
name: "Sync Repository Daily"

on:
  schedule:
    - cron: "15 3 * * *"  # Runs daily at 03:15 UTC
    
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: sapna-kokane/sof_test_repo_public
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          
      - name: set up git
        run: |
          git config --global user.name "sapna"
          git config --global user.email "sapna.kokane@amd.com"
      - name: Clone Public Repo
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
      - name: Push to private repository
        run: |
          git commit -a
          git commit -m "Daily sync from public repo"
          git push origin main
