---
name: "Sync Repository Daily"

on:
  schedule:
    - cron: "15 3 * * *"  # Runs daily at 03:15 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: sapna-kokane/sof_test_repo_public
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Clone Public Repo
        shell: bash
        run: |
          git clone --bare https://github.com/thesofproject/sof-test.git sof-test
          cd sof-test
          git push --mirror https://github.com/sapna-kokane/sof_test_repo_public.git"
        

      - name: Verify Sync Status
        shell: bash
        run: echo "Sync completed successfully!"
