name: Sync Public and Private Repositories

on:
  #schedule:
  #  - cron: "0 0 * * *" # Runs daily at midnight UTC
 # pull_request:
   # branches:
     # - main
  workflow_dispatch:

jobs:
  sync_repo:
    runs-on: ubuntu-latest
    env:
      branch_name: main

    steps:
      # Step 1: Checkout Private Repository
      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: sapna-kokane/sof_test_repo_public
          path: sound
          fetch-depth: 0
          ref: ${{ env.branch_name }}

      # Step 2: Remove existing public-repo directory (if exists)
      - name: Remove existing public-repo directory
        run: rm -rf public-repo

      # Step 3: Clone Public Repository
      - name: Clone Public Repository
        run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git public-repo

      # Step 4: Configure Git
      - name: Configure Git
        run: |
          cd $GITHUB_WORKSPACE/sound
          git config user.name "sapna kokane"
          git config user.email "sapna.kokane@amd.com"
      # Step 5: Sync Public to Private Repository (Exclude Dockerfile)
      - name: Sync Public to Private Repository
        run: |
          rsync -av --exclude='.git' --exclude='Dockerfile' public-repo/ private-repo/
          cd private-repo
          git add --all
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Exiting with success."
            exit 0
          else
            git commit -m "Sync with public repository"
            git push origin ${{ env.branch_name }}
          fi
