name: Sync Public and Private Repositories

on:
#  schedule:
#    - cron: "0 0 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_repo:
    runs-on: windows-latest
    env:
      branch_name: main
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: sapna-kokane/sof_test_repo_public
          path: private-repo
          fetch-depth: 0
          ref: ${{ env.branch_name }}

      - name: Remove existing public-repo directory (if exists)
        run: rm -rf public-repo

      - name: Clone Public Repository
        run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git public-repo

      - name: Configure Git
        run: |
          git config user.name "sapna kokane"
          git config user.email "sapna.kokane@amd.com"

      - name: Sync Public to Private Repository
        run: |
          set -e
          echo "Starting sync process..."
          rsync -av --exclude='.git' public-repo/ private-repo/
          echo "Sync completed. Preparing to commit changes..."
          cd private-repo
          git add --all
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Exiting with success."
            exit 0
          else
            git commit -m "Sync with public repository"
            git lfs push origin ${{ env.branch_name }}
            git push origin ${{ env.branch_name }}
          fi

      - name: Cleanup
        run: rm -rf public-repo private-repo
