name: Sync Public and Private Repositories

on:
  # schedule:
  #   - cron: "0 0 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_repo:
    runs-on: self-hosted
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: sapna-kokane/sof_test_repo_public
          path: private-repo
          fetch-depth: 0

      - name: Remove existing public-repo directory (if exists)
        run: rm -rf public-repo

      - name: Clone Public Repository
        run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git public-repo

      - name: Configure Git
        run: |
          git config user.name "sapna"
          git config user.email "sapna.kokane@amd.com"

      - name: Sync Public to Private Repository
        run: |
          rsync -av --exclude='.git' public-repo/ private-repo/
          cd private-repo
          git add --all
          git commit -m "Sync with public repository"
          git lfs push origin main
          git push origin main
