---
name: "Sync Repository Daily"

on:
  schedule:
    - cron: "15 3 * * *"  # Runs daily at 03:15 UTC

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2
      - name: set up git
        run: |
          git config --global user.name "sapna"
          git config --global user.email "sapna.kokane@amd.com"
      - name: Clone Public Repo
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
      - name: Copy files to private repo
        run: |
         cp -r sound/*.
      - name: Push to private repository
        run: |
          git add .
          git commit -m "Daily sync from public repo"
          git push origin main

        env: 
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
