---
name: "Sync Repository Daily"

on:
 # schedule:
 #   - cron: "15 3 * * *"  # Runs daily at 03:15 UTC
    
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: sapna-kokane/sof_test_repo_public
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: set up git
        shell: bash
        run: |
          git config --global user.name "sapna"
          git config --global user.email "sapna.kokane@amd.com"

      - name: Clone Public Repo
        shell: bash
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git

      - name: remove .git folder inside subdirectories
        shell: bash
        run: |
            rm -rf temp-public-repo/sound/.git || true

      - name: Push to private repository
        shell: bash
        run: |
          git add .
          git commit -m "Daily sync from public repo"
          git push origin main
      - name: Push changes
        run: |
          cd private-repo
          git push origin main
