---
name: "Sync Repository Daily"

on:
  schedule:
    - cron: "15 3 * * *"  # Runs daily at 03:15 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: sapna-kokane/sof_test_repo_public
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Clone Public Repo
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
          cd sound
          git log --oneline
      - name: Push to private repository
        run: |
          git remote remove origin
          git remote add origin https://github.com/sapna-kokane/sof_test_repo_public.git
          git branch -M main
          git push -u origin main --force
      - name: Verify Sync Status
        run: echo "Sync completed successfully!"
